sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - /snap/bin/hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $Deploy_Token
  keep-history: true
  on:
    branch: source
  target-branch: master
  local-dir: public
