[context.production.environment]
  HUGO_VERSION = "v0.64.1"

[build]
publish = "public"

command = "hugo --gc --minify --baseURL='https://gadelov.netlify.com/'    --disqusShortname = "yairgd-github-io-1  "
