[context.production.environment]
  HUGO_VERSION = "v0.64.1"

[build]
publish = "public"

command = "hugo --gc --minify --disableFastRender --baseURL='https://gadelov.netlify.com/'    --config=config.toml,a.toml server "
